// @ts-nocheck
// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// lovable-mcp-supabase-entry.ts
import mcp from "npm:C:\\Users\\usuario\\Documents\\Desktop\\reto\\reto-daily-habit\\src\\lib\\mcp\\index.ts";
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
declare const Deno: any;
Deno.serve(createSupabaseHandler(mcp, { functionName: "mcp" }));
