// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-challenges.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-challenges.ts
var list_challenges_default = defineTool({
  name: "list_challenges",
  title: "List challenges",
  description: "List the signed-in user's daily challenges with their current and target values.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("challenges").select("id, name, current_value, target_value, created_at").order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { challenges: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-challenge.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";
var create_challenge_default = defineTool2({
  name: "create_challenge",
  title: "Create challenge",
  description: "Create a new daily challenge for the signed-in user.",
  inputSchema: {
    name: z.string().trim().min(1).describe("Name of the challenge, e.g. '50 flexiones'."),
    target_value: z.number().int().positive().optional().describe("Daily target amount. Defaults to 1.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, target_value }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("challenges").insert({ user_id: ctx.getUserId(), name, target_value: target_value ?? 1 }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { challenge: data }
    };
  }
});

// src/lib/mcp/tools/update-challenge-progress.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var update_challenge_progress_default = defineTool3({
  name: "update_challenge_progress",
  title: "Update challenge progress",
  description: "Set the current progress value of one of the signed-in user's challenges.",
  inputSchema: {
    challenge_id: z2.string().uuid().describe("The challenge id, from list_challenges."),
    current_value: z2.number().int().min(0).describe("New current progress value.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ challenge_id, current_value }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("challenges").update({ current_value }).eq("id", challenge_id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) throw new ToolError("Challenge not found for this user.");
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { challenge: data }
    };
  }
});

// src/lib/mcp/tools/get-streak.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_streak_default = defineTool4({
  name: "get_streak",
  title: "Get streak",
  description: "Get the signed-in user's current daily streak count and last completed date.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_streaks").select("streak_count, last_completed_date").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const streak = data ?? { streak_count: 0, last_completed_date: null };
    return {
      content: [{ type: "text", text: JSON.stringify(streak) }],
      structuredContent: { streak }
    };
  }
});

// src/lib/mcp/tools/list-history.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_history_default = defineTool5({
  name: "list_history",
  title: "List history",
  description: "List the signed-in user's recent daily completion records, newest first.",
  inputSchema: {
    limit: z3.number().int().positive().optional().describe("How many days to return. Defaults to 30.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(limit ?? 30, 365);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("daily_records").select("date, all_completed, total_challenges, challenges_completed").order("date", { ascending: false }).limit(take);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { records: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_profile_default = defineTool6({
  name: "get_profile",
  title: "Get profile",
  description: "Get the signed-in user's fitness profile: display name, weight, height and goal.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("display_name, weight_kg, height_cm, fitness_goal").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/complete-today.ts
import { defineTool as defineTool7, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
function daysBetween(a, b) {
  return Math.abs(Math.round((new Date(b).getTime() - new Date(a).getTime()) / 864e5));
}
var complete_today_default = defineTool7({
  name: "complete_today",
  title: "Complete today's challenges",
  description: "Mark the signed-in user's challenges as completed for today: sets progress to the target, records the day in the history and updates the streak.",
  inputSchema: {
    challenge_ids: z4.array(z4.string().uuid()).optional().describe("Optional ids of specific challenges to complete. Omit to complete all of them."),
    date: z4.string().optional().describe("Optional day in YYYY-MM-DD format. Defaults to today.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ challenge_ids, date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = supabaseForUser(ctx);
    const day = date?.trim() || (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    if (!/^\d{4}-\d{2}-\d{2}$/.test(day)) {
      throw new ToolError2("date must be in YYYY-MM-DD format");
    }
    const { data: challenges, error: loadError } = await supabase.from("challenges").select("id, name, current_value, target_value");
    if (loadError) return { content: [{ type: "text", text: loadError.message }], isError: true };
    if (!challenges || challenges.length === 0) {
      throw new ToolError2("This user has no challenges to complete.");
    }
    let targets = challenges;
    if (challenge_ids && challenge_ids.length > 0) {
      const wanted = new Set(challenge_ids);
      targets = challenges.filter((c) => wanted.has(c.id));
      const missing = challenge_ids.filter((id) => !challenges.some((c) => c.id === id));
      if (missing.length > 0) {
        throw new ToolError2(`Challenge(s) not found for this user: ${missing.join(", ")}`);
      }
    }
    const toUpdate = targets.filter((c) => c.current_value < c.target_value);
    for (const c of toUpdate) {
      const { error } = await supabase.from("challenges").update({ current_value: c.target_value }).eq("id", c.id);
      if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const updated = challenges.map(
      (c) => targets.some((t) => t.id === c.id) ? { ...c, current_value: c.target_value } : c
    );
    const completed = updated.filter((c) => c.current_value >= c.target_value);
    const allCompleted = completed.length === updated.length;
    const { error: recordError } = await supabase.from("daily_records").upsert(
      {
        user_id: userId,
        date: day,
        challenges_completed: completed.map((c) => c.name),
        total_challenges: updated.length,
        all_completed: allCompleted
      },
      { onConflict: "user_id,date" }
    );
    if (recordError) {
      return { content: [{ type: "text", text: recordError.message }], isError: true };
    }
    const { data: streakRow } = await supabase.from("user_streaks").select("streak_count, last_completed_date").eq("user_id", userId).maybeSingle();
    let streakCount = streakRow?.streak_count ?? 0;
    const lastDate = streakRow?.last_completed_date ?? null;
    if (allCompleted && lastDate !== day) {
      streakCount = !lastDate || daysBetween(lastDate, day) > 1 ? 1 : streakCount + 1;
      const { error: streakError } = await supabase.from("user_streaks").upsert(
        { user_id: userId, streak_count: streakCount, last_completed_date: day },
        { onConflict: "user_id" }
      );
      if (streakError) {
        return { content: [{ type: "text", text: streakError.message }], isError: true };
      }
    }
    const summary = {
      date: day,
      completed: completed.map((c) => c.name),
      total_challenges: updated.length,
      all_completed: allCompleted,
      streak_count: streakCount
    };
    return {
      content: [
        {
          type: "text",
          text: allCompleted ? `Todos los retos de ${day} completados. Racha: ${streakCount} d\xEDa(s).` : `Retos marcados para ${day} (${completed.length}/${updated.length}). La racha avanza al completarlos todos.`
        }
      ],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xhynfigfoqngfhehrbpn";
var mcp_default = defineMcp({
  name: "daily-streak-tracker",
  title: "Daily Streak Tracker",
  version: "0.1.0",
  instructions: "Tools for Reto Diario, a daily challenge and streak tracker. Read and manage the signed-in user's challenges, daily progress, streaks and fitness profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_challenges_default,
    create_challenge_default,
    update_challenge_progress_default,
    complete_today_default,
    get_streak_default,
    list_history_default,
    get_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
